on: push
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean
      uses: heowc/action-hexo@main
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@main
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@main
      env:
        EMAIL: longzk@2980.com
        NAME: longzhaokun
      with:
        args: deploy
